#!/bin/sh
times=$1 # should be an integer
alias espeak='espeak -s 180 -v en-us'
# alias espeak='espeak -s 180 -v other/en-rp'
# alias espeak='espeak -s 180 -v other/en-n'

for i in $times; do
  espeak 'When I say value, you say comma'
  espeak Comma
  read
  espeak Comma
  read
done
