#!/bin/sh

value=$1
test -n "$value" || value=Value

delimiter=$2
test -n "$delimiter" || delimiter=comma

count=$3     # should be an integer
test -n "$count" || count=2

# alias espeak='espeak -s 180 -v en-us'
# alias espeak='espeak -s 180 -v other/en-rp'
# alias espeak='espeak -s 180 -v other/en-n'
which espeak > /dev/null || alias espeak='say -r 190'

for i in $(seq 1 $count); do
  espeak "When I say '$value', you say '$delimiter'"
  read
  espeak "$value"
  read
  espeak "$value"
  read
done
